//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Angajat
    {
        public int Id { get; set; }
        public string Cod_Angajat { get; set; }
        public string Nume_Prenume { get; set; }
        public int Ore_muncite { get; set; }
        public string CNP { get; set; }
        public System.DateTime Inceput_contract { get; set; }
    }
}
