//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concedii
    {
        public int Id { get; set; }
        public string Cod_angajat { get; set; }
        public System.DateTime Data_inceput_de_concediu { get; set; }
        public System.DateTime Data_sfarsit_de_concediu { get; set; }
    }
}
