//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Functii
    {
        public int Id { get; set; }
        public string Functie { get; set; }
        public int Program { get; set; }
        public decimal Salariu_de_baza { get; set; }
    }
}
