//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intrari
    {
        public int Id { get; set; }
        public string Cod_angajat { get; set; }
        public System.DateTime Ora_intrare { get; set; }
        public Nullable<System.DateTime> Ora_iesire { get; set; }
    }
}
