//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master
    {
        public int Id { get; set; }
        public string Cod_angajat { get; set; }
        public decimal Salariu { get; set; }
        public int Zi_scadenta { get; set; }
        public int Total_ore { get; set; }
        public int Flag { get; set; }
    }
}
