//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Angajat> Angajats { get; set; }
        public virtual DbSet<Concedii> Concediis { get; set; }
        public virtual DbSet<Functii> Functiis { get; set; }
        public virtual DbSet<Intrari> Intraris { get; set; }
        public virtual DbSet<Master> Masters { get; set; }
        public virtual DbSet<Salarii> Salariis { get; set; }
        public virtual DbSet<Sporuri> Sporuris { get; set; }
        public virtual DbSet<ListaVechimeAngajat> ListaVechimeAngajats { get; set; }
        public virtual DbSet<TopAngajati> TopAngajatis { get; set; }
        public virtual DbSet<VedereSalarii> VedereSalariis { get; set; }
        public virtual DbSet<VedereSalariiNet> VedereSalariiNets { get; set; }
    
        public virtual ObjectResult<string> AngajatiDupaFunctii(Nullable<int> functie)
        {
            var functieParameter = functie.HasValue ?
                new ObjectParameter("functie", functie) :
                new ObjectParameter("functie", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("AngajatiDupaFunctii", functieParameter);
        }
    
        public virtual ObjectResult<VerificaConcediuAngajat_Result> VerificaConcediuAngajat(string nume_angajat)
        {
            var nume_angajatParameter = nume_angajat != null ?
                new ObjectParameter("nume_angajat", nume_angajat) :
                new ObjectParameter("nume_angajat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerificaConcediuAngajat_Result>("VerificaConcediuAngajat", nume_angajatParameter);
        }
    }
}
